//! Raw FFI bindings to [GTCaca](https://github.com/stricaud/gtcaca), a
//! libcaca-based terminal UI toolkit.
//!
//! This crate exposes the C API verbatim (generated by bindgen) and links the
//! GTCaca C sources together with libcaca. It is `unsafe` by nature — for a
//! safe, idiomatic interface use the [`gtcaca`](https://crates.io/crates/gtcaca)
//! crate.
//!
//! libcaca must be installed on the system (found via pkg-config at build time):
//! `apt install libcaca-dev`, `dnf install libcaca-devel`, or
//! `brew install libcaca`.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
