/* gtcaca_api.h — GENERATED by tools/gen_docs.py — do not edit */
#ifndef GTCACA_API_H
#define GTCACA_API_H

typedef struct {
  const char *name;
  const char *module;
  const char *brief;
  const char *signature;
  const char *description;
  const char *params;   /* "param_name\tdescription\n" per param */
  const char *returns;
} gtcaca_api_entry_t;

extern const gtcaca_api_entry_t gtcaca_api[];
extern const int gtcaca_api_count;

#endif /* GTCACA_API_H */
