/* gtcaca_api.c — GENERATED by tools/gen_docs.py — do not edit */
#include "gtcaca_api.h"

const gtcaca_api_entry_t gtcaca_api[] = {
  {
    /* gtcaca_application_draw */
    "gtcaca_application_draw",
    "application",
    "Draw the application widget",
    "void gtcaca_application_draw(gtcaca_application_widget_t *application)",
    "Renders the application widget onto the caca canvas.\n"
    "Called automatically by the main loop; you normally do not need\n"
    "to call this directly unless you perform a manual redraw.",
    "application\\tThe application argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_vbox_new */
    "gtcaca_vbox_new",
    "box",
    "Create a new vertical box layout",
    "gtcaca_box_t * gtcaca_vbox_new(void)",
    "Convenience constructor for a vertically-stacking box layout.\n"
    "Equivalent to gtcaca_box_new(GTCACA_BOX_VERTICAL).",
    "",
    "Pointer to the new box layout, or NULL on allocation failure."
  },
  {
    /* gtcaca_hbox_new */
    "gtcaca_hbox_new",
    "box",
    "Create a new horizontal box layout",
    "gtcaca_box_t * gtcaca_hbox_new(void)",
    "Convenience constructor for a horizontally-stacking box layout.\n"
    "Equivalent to gtcaca_box_new(GTCACA_BOX_HORIZONTAL).",
    "",
    "Pointer to the new box layout, or NULL on allocation failure."
  },
  {
    /* gtcaca_box_new */
    "gtcaca_box_new",
    "box",
    "Create a new box layout",
    "gtcaca_box_t * gtcaca_box_new(gtcaca_box_orientation_t orientation)",
    "Allocates a box layout with the given orientation. A box does not\n"
    "draw anything: it positions the widgets you add to it. Add widgets\n"
    "and nested boxes, then call gtcaca_box_apply() (or _apply_window) to\n"
    "compute their coordinates. Free it with gtcaca_box_free().",
    "orientation\\tThe orientation argument\\n",
    "Pointer to the new box layout, or NULL on allocation failure."
  },
  {
    /* gtcaca_box_add */
    "gtcaca_box_add",
    "box",
    "Add a widget to the box at its natural size",
    "void gtcaca_box_add(gtcaca_box_t *box, gtcaca_widget_t *widget)",
    "Appends an already-created widget to the box. The widget keeps its\n"
    "natural size and is aligned on the cross axis per the box alignment.",
    "box\\tThe box argument\\nwidget\\tTarget widget\\n",
    "Nothing."
  },
  {
    /* gtcaca_box_add_expand */
    "gtcaca_box_add_expand",
    "box",
    "Add a widget that grows to fill leftover space",
    "void gtcaca_box_add_expand(gtcaca_box_t *box, gtcaca_widget_t *widget)",
    "Appends a widget that both expands to share the leftover space along\n"
    "the box's main axis and is resized to fill the cell it is given.\n"
    "Use it for the widget that should soak up the remaining room.",
    "box\\tThe box argument\\nwidget\\tTarget widget\\n",
    "Nothing."
  },
  {
    /* gtcaca_box_add_full */
    "gtcaca_box_add_full",
    "box",
    "Add a widget with explicit expand/fill flags",
    "void gtcaca_box_add_full(gtcaca_box_t *box, gtcaca_widget_t *widget, int expand, int fill)",
    "Appends a widget with full control: expand shares leftover main-axis\n"
    "space between growable items; fill resizes the widget to its cell.\n"
    "gtcaca_box_add() is (0,0); gtcaca_box_add_expand() is (1,1).",
    "box\\tThe box argument\\nwidget\\tTarget widget\\nexpand\\tThe expand argument\\nfill\\tThe fill argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_box_add_box */
    "gtcaca_box_add_box",
    "box",
    "Nest a child box inside this box",
    "void gtcaca_box_add_box(gtcaca_box_t *box, gtcaca_box_t *child)",
    "Adds a nested box as an item. The child spans the full cross axis and\n"
    "takes its natural size along the main axis (add a stretch if you want\n"
    "it to absorb slack). The child is laid out recursively on apply.",
    "box\\tThe box argument\\nchild\\tThe child argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_box_add_stretch */
    "gtcaca_box_add_stretch",
    "box",
    "Add a flexible spacer that pushes items apart",
    "void gtcaca_box_add_stretch(gtcaca_box_t *box)",
    "Adds an empty, infinitely-flexible item (Qt's addStretch). It claims\n"
    "an equal share of the leftover space, so stretches before/after/\n"
    "between widgets align them to the end, start or spread them out.",
    "box\\tThe box argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_box_add_spacing */
    "gtcaca_box_add_spacing",
    "box",
    "Add a fixed-size empty gap",
    "void gtcaca_box_add_spacing(gtcaca_box_t *box, int size)",
    "Inserts a fixed empty gap of `size` cells along the box's main axis,\n"
    "on top of the regular inter-item spacing.",
    "box\\tThe box argument\\nsize\\tThe size argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_box_set_spacing */
    "gtcaca_box_set_spacing",
    "box",
    "Set the gap between items",
    "void gtcaca_box_set_spacing(gtcaca_box_t *box, int spacing)",
    "Sets the number of blank cells inserted between adjacent items along\n"
    "the main axis. Defaults to 1.",
    "box\\tThe box argument\\nspacing\\tThe spacing argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_box_set_margin */
    "gtcaca_box_set_margin",
    "box",
    "Set the outer margin",
    "void gtcaca_box_set_margin(gtcaca_box_t *box, int margin)",
    "Sets the blank border, in cells, kept on every side inside the box's\n"
    "rectangle before items are placed. Defaults to 1.",
    "box\\tThe box argument\\nmargin\\tThe margin argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_box_set_align */
    "gtcaca_box_set_align",
    "box",
    "Set the cross-axis alignment",
    "void gtcaca_box_set_align(gtcaca_box_t *box, gtcaca_align_t align)",
    "Sets how non-filling items are aligned on the cross axis: START,\n"
    "CENTER or END. Defaults to START.",
    "box\\tThe box argument\\nalign\\tThe align argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_box_preferred_width */
    "gtcaca_box_preferred_width",
    "box",
    "Compute the box's natural width",
    "int gtcaca_box_preferred_width(gtcaca_box_t *box)",
    "Returns the width the box would like, accounting for its items,\n"
    "inter-item spacing and margins. Nested boxes are measured recursively.",
    "box\\tThe box argument\\n",
    "Preferred width in characters."
  },
  {
    /* gtcaca_box_preferred_height */
    "gtcaca_box_preferred_height",
    "box",
    "Compute the box's natural height",
    "int gtcaca_box_preferred_height(gtcaca_box_t *box)",
    "Returns the height the box would like, accounting for its items,\n"
    "inter-item spacing and margins. Nested boxes are measured recursively.",
    "box\\tThe box argument\\n",
    "Preferred height in characters."
  },
  {
    /* gtcaca_box_apply */
    "gtcaca_box_apply",
    "box",
    "Lay out the box over a rectangle",
    "void gtcaca_box_apply(gtcaca_box_t *box, int x, int y, int width, int height)",
    "Positions every managed widget within the given canvas rectangle by\n"
    "overwriting its x/y/width/height. Call once after building the box;\n"
    "the next redraw paints the widgets at their computed positions.",
    "box\\tThe box argument\\nx\\tX position relative to parent\\ny\\tY position relative to parent\\nwidth\\tWidth in characters\\nheight\\tHeight in characters\\n",
    "Nothing."
  },
  {
    /* gtcaca_box_apply_window */
    "gtcaca_box_apply_window",
    "box",
    "Lay out the box inside a window",
    "void gtcaca_box_apply_window(gtcaca_box_t *box, gtcaca_window_widget_t *win)",
    "Convenience wrapper around gtcaca_box_apply() that targets the\n"
    "interior of a window, just inside its border.",
    "box\\tThe box argument\\nwin\\tThe win argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_box_free */
    "gtcaca_box_free",
    "box",
    "Free the box and its nested boxes",
    "void gtcaca_box_free(gtcaca_box_t *box)",
    "Releases the box and any boxes nested inside it. The widgets the box\n"
    "positioned are never freed and remain valid.",
    "box\\tThe box argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_button_key_cb_register */
    "gtcaca_button_key_cb_register",
    "button",
    "Register a callback for button key events",
    "int gtcaca_button_key_cb_register(gtcaca_button_widget_t *widget, gtcaca_button_key_cb_t key_cb)",
    "Registers a callback function that is invoked whenever a key event\n"
    "reaches the button key widget. The callback receives the widget pointer,\n"
    "the key code, and the userdata pointer supplied here.",
    "widget\\tTarget widget\\nkey_cb\\tCallback function pointer\\n",
    "0 on success, non-zero on error."
  },
  {
    /* gtcaca_button_draw_press_noshade */
    "gtcaca_button_draw_press_noshade",
    "button",
    "Perform button draw press noshade operation",
    "void gtcaca_button_draw_press_noshade(gtcaca_button_widget_t *button)",
    "Perform button draw press noshade operation.",
    "button\\tThe button argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_button_draw */
    "gtcaca_button_draw",
    "button",
    "Draw the button widget",
    "void gtcaca_button_draw(gtcaca_button_widget_t *button)",
    "Renders the button widget onto the caca canvas.\n"
    "Called automatically by the main loop; you normally do not need\n"
    "to call this directly unless you perform a manual redraw.",
    "button\\tThe button argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_checkbox_draw */
    "gtcaca_checkbox_draw",
    "checkbox",
    "Draw the checkbox widget",
    "void gtcaca_checkbox_draw(gtcaca_checkbox_widget_t *checkbox)",
    "Renders the checkbox widget onto the caca canvas.\n"
    "Called automatically by the main loop; you normally do not need\n"
    "to call this directly unless you perform a manual redraw.",
    "checkbox\\tThe checkbox argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_checkbox_key_cb_register */
    "gtcaca_checkbox_key_cb_register",
    "checkbox",
    "Register a callback for checkbox key events",
    "int gtcaca_checkbox_key_cb_register(gtcaca_checkbox_widget_t *widget, gtcaca_checkbox_key_cb_t key_cb, void *userdata)",
    "Registers a callback function that is invoked whenever a key event\n"
    "reaches the checkbox key widget. The callback receives the widget pointer,\n"
    "the key code, and the userdata pointer supplied here.",
    "widget\\tTarget widget\\nkey_cb\\tCallback function pointer\\nuserdata\\tUser-supplied pointer passed back in callbacks\\n",
    "0 on success, non-zero on error."
  },
  {
    /* gtcaca_checkbox_get_checked */
    "gtcaca_checkbox_get_checked",
    "checkbox",
    "Get the checked property of checkbox",
    "int gtcaca_checkbox_get_checked(gtcaca_checkbox_widget_t *checkbox)",
    "Returns the current checked attribute of the checkbox widget.",
    "checkbox\\tThe checkbox argument\\n",
    "0 on success, non-zero on error."
  },
  {
    /* gtcaca_checkbox_set_checked */
    "gtcaca_checkbox_set_checked",
    "checkbox",
    "Set the checked property of checkbox",
    "void gtcaca_checkbox_set_checked(gtcaca_checkbox_widget_t *checkbox, int checked)",
    "Sets the checked attribute of the checkbox widget to the given value.",
    "checkbox\\tThe checkbox argument\\nchecked\\tNon-zero to check, 0 to uncheck\\n",
    "Nothing."
  },
  {
    /* gtcaca_combobox_draw */
    "gtcaca_combobox_draw",
    "combobox",
    "Draw the combobox widget",
    "void gtcaca_combobox_draw(gtcaca_combobox_widget_t *cb)",
    "Renders the combobox widget onto the caca canvas.\n"
    "Called automatically by the main loop; you normally do not need\n"
    "to call this directly unless you perform a manual redraw.",
    "cb\\tCallback function pointer\\n",
    "Nothing."
  },
  {
    /* gtcaca_combobox_append */
    "gtcaca_combobox_append",
    "combobox",
    "Append an item to the combobox",
    "void gtcaca_combobox_append(gtcaca_combobox_widget_t *cb, const char *item)",
    "Appends a new entry to the combobox. The string is copied internally.",
    "cb\\tCallback function pointer\\nitem\\tItem string to add\\n",
    "Nothing."
  },
  {
    /* gtcaca_combobox_key_cb_register */
    "gtcaca_combobox_key_cb_register",
    "combobox",
    "Register a callback for combobox key events",
    "int gtcaca_combobox_key_cb_register(gtcaca_combobox_widget_t *widget, gtcaca_combobox_key_cb_t key_cb, void *userdata)",
    "Registers a callback function that is invoked whenever a key event\n"
    "reaches the combobox key widget. The callback receives the widget pointer,\n"
    "the key code, and the userdata pointer supplied here.",
    "widget\\tTarget widget\\nkey_cb\\tCallback function pointer\\nuserdata\\tUser-supplied pointer passed back in callbacks\\n",
    "0 on success, non-zero on error."
  },
  {
    /* gtcaca_combobox_get_selected_index */
    "gtcaca_combobox_get_selected_index",
    "combobox",
    "Perform combobox get selected index operation",
    "int gtcaca_combobox_get_selected_index(gtcaca_combobox_widget_t *cb)",
    "Perform combobox get selected index operation.",
    "cb\\tCallback function pointer\\n",
    "0 on success, non-zero on error."
  },
  {
    /* gtcaca_entry_draw */
    "gtcaca_entry_draw",
    "entry",
    "Draw the entry widget",
    "void gtcaca_entry_draw(gtcaca_entry_widget_t *entry)",
    "Renders the entry widget onto the caca canvas.\n"
    "Called automatically by the main loop; you normally do not need\n"
    "to call this directly unless you perform a manual redraw.",
    "entry\\tThe entry argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_entry_key_cb_register */
    "gtcaca_entry_key_cb_register",
    "entry",
    "Register a callback for entry key events",
    "int gtcaca_entry_key_cb_register(gtcaca_entry_widget_t *widget, gtcaca_entry_key_cb_t key_cb, void *userdata)",
    "Registers a callback function that is invoked whenever a key event\n"
    "reaches the entry key widget. The callback receives the widget pointer,\n"
    "the key code, and the userdata pointer supplied here.",
    "widget\\tTarget widget\\nkey_cb\\tCallback function pointer\\nuserdata\\tUser-supplied pointer passed back in callbacks\\n",
    "0 on success, non-zero on error."
  },
  {
    /* gtcaca_entry_set_text */
    "gtcaca_entry_set_text",
    "entry",
    "Set the text property of entry",
    "void gtcaca_entry_set_text(gtcaca_entry_widget_t *entry, const char *text)",
    "Sets the text attribute of the entry widget to the given value.",
    "entry\\tThe entry argument\\ntext\\tText label to display\\n",
    "Nothing."
  },
  {
    /* gtcaca_entry_set_secret */
    "gtcaca_entry_set_secret",
    "entry",
    "Set the secret property of entry",
    "void gtcaca_entry_set_secret(gtcaca_entry_widget_t *entry, int secret)",
    "Sets the secret attribute of the entry widget to the given value.",
    "entry\\tThe entry argument\\nsecret\\tNon-zero to hide text (password mode)\\n",
    "Nothing."
  },
  {
    /* gtcaca_expander_draw */
    "gtcaca_expander_draw",
    "expander",
    "Draw the expander widget",
    "void gtcaca_expander_draw(gtcaca_expander_widget_t *exp)",
    "Renders the expander widget onto the caca canvas.\n"
    "Called automatically by the main loop; you normally do not need\n"
    "to call this directly unless you perform a manual redraw.",
    "exp\\tThe exp argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_expander_handle_key */
    "gtcaca_expander_handle_key",
    "expander",
    "Perform expander handle key operation",
    "void gtcaca_expander_handle_key(gtcaca_expander_widget_t *exp, int key)",
    "Perform expander handle key operation.",
    "exp\\tThe exp argument\\nkey\\tKey code that was pressed\\n",
    "Nothing."
  },
  {
    /* gtcaca_expander_add_managed */
    "gtcaca_expander_add_managed",
    "expander",
    "Perform expander add managed operation",
    "void gtcaca_expander_add_managed(gtcaca_expander_widget_t *exp, gtcaca_widget_t *widget)",
    "Perform expander add managed operation.",
    "exp\\tThe exp argument\\nwidget\\tTarget widget\\n",
    "Nothing."
  },
  {
    /* gtcaca_expander_set_expanded */
    "gtcaca_expander_set_expanded",
    "expander",
    "Set the expanded property of expander",
    "void gtcaca_expander_set_expanded(gtcaca_expander_widget_t *exp, int expanded)",
    "Sets the expanded attribute of the expander widget to the given value.",
    "exp\\tThe exp argument\\nexpanded\\tNon-zero to expand, 0 to collapse\\n",
    "Nothing."
  },
  {
    /* gtcaca_expander_get_expanded */
    "gtcaca_expander_get_expanded",
    "expander",
    "Get the expanded property of expander",
    "int gtcaca_expander_get_expanded(gtcaca_expander_widget_t *exp)",
    "Returns the current expanded attribute of the expander widget.",
    "exp\\tThe exp argument\\n",
    "0 on success, non-zero on error."
  },
  {
    /* gtcaca_expander_cb_register */
    "gtcaca_expander_cb_register",
    "expander",
    "Register a callback for expander events",
    "void gtcaca_expander_cb_register(gtcaca_expander_widget_t *exp, gtcaca_expander_cb_t cb, void *userdata)",
    "Registers a callback function that is invoked whenever a key event\n"
    "reaches the expander widget. The callback receives the widget pointer,\n"
    "the key code, and the userdata pointer supplied here.",
    "exp\\tThe exp argument\\ncb\\tCallback function pointer\\nuserdata\\tUser-supplied pointer passed back in callbacks\\n",
    "Nothing."
  },
  {
    /* gtcaca_frame_draw */
    "gtcaca_frame_draw",
    "frame",
    "Draw the frame widget",
    "void gtcaca_frame_draw(gtcaca_frame_widget_t *frame)",
    "Renders the frame widget onto the caca canvas.\n"
    "Called automatically by the main loop; you normally do not need\n"
    "to call this directly unless you perform a manual redraw.",
    "frame\\tThe frame argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_image_load */
    "gtcaca_image_load",
    "image",
    "Perform image load operation",
    "int gtcaca_image_load(gtcaca_image_widget_t *img, const char *filepath)",
    "Perform image load operation.",
    "img\\tThe img argument\\nfilepath\\tPath to the image file\\n",
    "0 on success, non-zero on error."
  },
  {
    /* gtcaca_image_draw */
    "gtcaca_image_draw",
    "image",
    "Draw the image widget",
    "void gtcaca_image_draw(gtcaca_image_widget_t *img)",
    "Renders the image widget onto the caca canvas.\n"
    "Called automatically by the main loop; you normally do not need\n"
    "to call this directly unless you perform a manual redraw.",
    "img\\tThe img argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_image_free */
    "gtcaca_image_free",
    "image",
    "Free the image widget and its resources",
    "void gtcaca_image_free(gtcaca_image_widget_t *img)",
    "Free the image widget and its resources.",
    "img\\tThe img argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_label_draw */
    "gtcaca_label_draw",
    "label",
    "Draw the label widget",
    "void gtcaca_label_draw(gtcaca_label_widget_t *label)",
    "Renders the label widget onto the caca canvas.\n"
    "Called automatically by the main loop; you normally do not need\n"
    "to call this directly unless you perform a manual redraw.",
    "label\\tText label to display\\n",
    "Nothing."
  },
  {
    /* gtcaca_main */
    "gtcaca_main",
    "main",
    "Perform main operation",
    "void gtcaca_main(void)",
    "Perform main operation.",
    "",
    "Nothing."
  },
  {
    /* gtcaca_redraw */
    "gtcaca_redraw",
    "main",
    "Perform redraw operation",
    "void gtcaca_redraw(void)",
    "Perform redraw operation.",
    "",
    "Nothing."
  },
  {
    /* gtcaca_get_newid */
    "gtcaca_get_newid",
    "main",
    "Get the newid of ",
    "unsigned int gtcaca_get_newid(void)",
    "Returns the current newid attribute of the  widget.",
    "",
    "Result value."
  },
  {
    /* gtcaca_menu_draw */
    "gtcaca_menu_draw",
    "menu",
    "Draw the menu widget",
    "void gtcaca_menu_draw(gtcaca_menu_widget_t *menu)",
    "Renders the menu widget onto the caca canvas.\n"
    "Called automatically by the main loop; you normally do not need\n"
    "to call this directly unless you perform a manual redraw.",
    "menu\\tMenu widget\\n",
    "Nothing."
  },
  {
    /* gtcaca_menu_add_entry */
    "gtcaca_menu_add_entry",
    "menu",
    "Perform menu add entry operation",
    "int gtcaca_menu_add_entry(gtcaca_menu_widget_t *menu, const char *title)",
    "Perform menu add entry operation.",
    "menu\\tMenu widget\\ntitle\\tText label to display\\n",
    "0 on success, non-zero on error."
  },
  {
    /* gtcaca_menu_add_item */
    "gtcaca_menu_add_item",
    "menu",
    "Perform menu add item operation",
    "int gtcaca_menu_add_item(gtcaca_menu_widget_t *menu, int entry_idx, const char *label, const char *shortcut, gtcaca_menu_action_t action, void *userdata)",
    "Perform menu add item operation.",
    "menu\\tMenu widget\\nentry_idx\\tMenu entry index\\nlabel\\tText label to display\\nshortcut\\tKeyboard shortcut string\\naction\\tThe action argument\\nuserdata\\tUser-supplied pointer passed back in callbacks\\n",
    "0 on success, non-zero on error."
  },
  {
    /* gtcaca_menu_add_separator */
    "gtcaca_menu_add_separator",
    "menu",
    "Perform menu add separator operation",
    "int gtcaca_menu_add_separator(gtcaca_menu_widget_t *menu, int entry_idx)",
    "Perform menu add separator operation.",
    "menu\\tMenu widget\\nentry_idx\\tMenu entry index\\n",
    "0 on success, non-zero on error."
  },
  {
    /* gtcaca_menu_handle_key */
    "gtcaca_menu_handle_key",
    "menu",
    "Perform menu handle key operation",
    "int gtcaca_menu_handle_key(gtcaca_menu_widget_t *menu, int key)",
    "Perform menu handle key operation.",
    "menu\\tMenu widget\\nkey\\tKey code that was pressed\\n",
    "0 on success, non-zero on error."
  },
  {
    /* gtcaca_progressbar_draw */
    "gtcaca_progressbar_draw",
    "progressbar",
    "Draw the progressbar widget",
    "void gtcaca_progressbar_draw(gtcaca_progressbar_widget_t *pb)",
    "Renders the progressbar widget onto the caca canvas.\n"
    "Called automatically by the main loop; you normally do not need\n"
    "to call this directly unless you perform a manual redraw.",
    "pb\\tThe pb argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_progressbar_set_value */
    "gtcaca_progressbar_set_value",
    "progressbar",
    "Set the value property of progressbar",
    "void gtcaca_progressbar_set_value(gtcaca_progressbar_widget_t *pb, float value)",
    "Sets the value attribute of the progressbar widget to the given value.",
    "pb\\tThe pb argument\\nvalue\\tNew value to set\\n",
    "Nothing."
  },
  {
    /* gtcaca_progressbar_get_value */
    "gtcaca_progressbar_get_value",
    "progressbar",
    "Get the value property of progressbar",
    "float gtcaca_progressbar_get_value(gtcaca_progressbar_widget_t *pb)",
    "Returns the current value attribute of the progressbar widget.",
    "pb\\tThe pb argument\\n",
    "The current value."
  },
  {
    /* gtcaca_radiobutton_draw */
    "gtcaca_radiobutton_draw",
    "radiobutton",
    "Draw the radiobutton widget",
    "void gtcaca_radiobutton_draw(gtcaca_radiobutton_widget_t *rb)",
    "Renders the radiobutton widget onto the caca canvas.\n"
    "Called automatically by the main loop; you normally do not need\n"
    "to call this directly unless you perform a manual redraw.",
    "rb\\tThe rb argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_radiobutton_key_cb_register */
    "gtcaca_radiobutton_key_cb_register",
    "radiobutton",
    "Register a callback for radiobutton key events",
    "int gtcaca_radiobutton_key_cb_register(gtcaca_radiobutton_widget_t *widget, gtcaca_radiobutton_key_cb_t key_cb, void *userdata)",
    "Registers a callback function that is invoked whenever a key event\n"
    "reaches the radiobutton key widget. The callback receives the widget pointer,\n"
    "the key code, and the userdata pointer supplied here.",
    "widget\\tTarget widget\\nkey_cb\\tCallback function pointer\\nuserdata\\tUser-supplied pointer passed back in callbacks\\n",
    "0 on success, non-zero on error."
  },
  {
    /* gtcaca_radiobutton_get_active */
    "gtcaca_radiobutton_get_active",
    "radiobutton",
    "Get the active property of radiobutton",
    "int gtcaca_radiobutton_get_active(gtcaca_radiobutton_widget_t *rb)",
    "Returns the current active attribute of the radiobutton widget.",
    "rb\\tThe rb argument\\n",
    "0 on success, non-zero on error."
  },
  {
    /* gtcaca_radiobutton_set_active */
    "gtcaca_radiobutton_set_active",
    "radiobutton",
    "Set the active property of radiobutton",
    "void gtcaca_radiobutton_set_active(gtcaca_radiobutton_widget_t *rb)",
    "Sets the active attribute of the radiobutton widget to the given value.",
    "rb\\tThe rb argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_scale_draw */
    "gtcaca_scale_draw",
    "scale",
    "Draw the scale widget",
    "void gtcaca_scale_draw(gtcaca_scale_widget_t *scale)",
    "Renders the scale widget onto the caca canvas.\n"
    "Called automatically by the main loop; you normally do not need\n"
    "to call this directly unless you perform a manual redraw.",
    "scale\\tThe scale argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_scale_handle_key */
    "gtcaca_scale_handle_key",
    "scale",
    "Perform scale handle key operation",
    "void gtcaca_scale_handle_key(gtcaca_scale_widget_t *scale, int key)",
    "Perform scale handle key operation.",
    "scale\\tThe scale argument\\nkey\\tKey code that was pressed\\n",
    "Nothing."
  },
  {
    /* gtcaca_scale_set_value */
    "gtcaca_scale_set_value",
    "scale",
    "Set the value property of scale",
    "void gtcaca_scale_set_value(gtcaca_scale_widget_t *scale, double value)",
    "Sets the value attribute of the scale widget to the given value.",
    "scale\\tThe scale argument\\nvalue\\tNew value to set\\n",
    "Nothing."
  },
  {
    /* gtcaca_scale_get_value */
    "gtcaca_scale_get_value",
    "scale",
    "Get the value property of scale",
    "double gtcaca_scale_get_value(gtcaca_scale_widget_t *scale)",
    "Returns the current value attribute of the scale widget.",
    "scale\\tThe scale argument\\n",
    "The current value."
  },
  {
    /* gtcaca_scale_cb_register */
    "gtcaca_scale_cb_register",
    "scale",
    "Register a callback for scale events",
    "void gtcaca_scale_cb_register(gtcaca_scale_widget_t *scale, gtcaca_scale_cb_t cb, void *userdata)",
    "Registers a callback function that is invoked whenever a key event\n"
    "reaches the scale widget. The callback receives the widget pointer,\n"
    "the key code, and the userdata pointer supplied here.",
    "scale\\tThe scale argument\\ncb\\tCallback function pointer\\nuserdata\\tUser-supplied pointer passed back in callbacks\\n",
    "Nothing."
  },
  {
    /* gtcaca_separator_draw */
    "gtcaca_separator_draw",
    "separator",
    "Draw the separator widget",
    "void gtcaca_separator_draw(gtcaca_separator_widget_t *sep)",
    "Renders the separator widget onto the caca canvas.\n"
    "Called automatically by the main loop; you normally do not need\n"
    "to call this directly unless you perform a manual redraw.",
    "sep\\tThe sep argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_spinbutton_draw */
    "gtcaca_spinbutton_draw",
    "spinbutton",
    "Draw the spinbutton widget",
    "void gtcaca_spinbutton_draw(gtcaca_spinbutton_widget_t *sb)",
    "Renders the spinbutton widget onto the caca canvas.\n"
    "Called automatically by the main loop; you normally do not need\n"
    "to call this directly unless you perform a manual redraw.",
    "sb\\tThe sb argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_spinbutton_handle_key */
    "gtcaca_spinbutton_handle_key",
    "spinbutton",
    "Perform spinbutton handle key operation",
    "void gtcaca_spinbutton_handle_key(gtcaca_spinbutton_widget_t *sb, int key)",
    "Perform spinbutton handle key operation.",
    "sb\\tThe sb argument\\nkey\\tKey code that was pressed\\n",
    "Nothing."
  },
  {
    /* gtcaca_spinbutton_set_value */
    "gtcaca_spinbutton_set_value",
    "spinbutton",
    "Set the value property of spinbutton",
    "void gtcaca_spinbutton_set_value(gtcaca_spinbutton_widget_t *sb, double value)",
    "Sets the value attribute of the spinbutton widget to the given value.",
    "sb\\tThe sb argument\\nvalue\\tNew value to set\\n",
    "Nothing."
  },
  {
    /* gtcaca_spinbutton_get_value */
    "gtcaca_spinbutton_get_value",
    "spinbutton",
    "Get the value property of spinbutton",
    "double gtcaca_spinbutton_get_value(gtcaca_spinbutton_widget_t *sb)",
    "Returns the current value attribute of the spinbutton widget.",
    "sb\\tThe sb argument\\n",
    "The current value."
  },
  {
    /* gtcaca_spinbutton_cb_register */
    "gtcaca_spinbutton_cb_register",
    "spinbutton",
    "Register a callback for spinbutton events",
    "void gtcaca_spinbutton_cb_register(gtcaca_spinbutton_widget_t *sb, gtcaca_spinbutton_cb_t cb, void *userdata)",
    "Registers a callback function that is invoked whenever a key event\n"
    "reaches the spinbutton widget. The callback receives the widget pointer,\n"
    "the key code, and the userdata pointer supplied here.",
    "sb\\tThe sb argument\\ncb\\tCallback function pointer\\nuserdata\\tUser-supplied pointer passed back in callbacks\\n",
    "Nothing."
  },
  {
    /* gtcaca_spinner_draw */
    "gtcaca_spinner_draw",
    "spinner",
    "Draw the spinner widget",
    "void gtcaca_spinner_draw(gtcaca_spinner_widget_t *sp)",
    "Renders the spinner widget onto the caca canvas.\n"
    "Called automatically by the main loop; you normally do not need\n"
    "to call this directly unless you perform a manual redraw.",
    "sp\\tThe sp argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_spinner_set_spinning */
    "gtcaca_spinner_set_spinning",
    "spinner",
    "Set the spinning property of spinner",
    "void gtcaca_spinner_set_spinning(gtcaca_spinner_widget_t *sp, int spinning)",
    "Sets the spinning attribute of the spinner widget to the given value.",
    "sp\\tThe sp argument\\nspinning\\tNon-zero to start spinning, 0 to stop\\n",
    "Nothing."
  },
  {
    /* gtcaca_spinner_step */
    "gtcaca_spinner_step",
    "spinner",
    "Perform spinner step operation",
    "void gtcaca_spinner_step(gtcaca_spinner_widget_t *sp)",
    "Perform spinner step operation.",
    "sp\\tThe sp argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_statusbar_draw */
    "gtcaca_statusbar_draw",
    "statusbar",
    "Draw the statusbar widget",
    "void gtcaca_statusbar_draw(gtcaca_statusbar_widget_t *sb)",
    "Renders the statusbar widget onto the caca canvas.\n"
    "Called automatically by the main loop; you normally do not need\n"
    "to call this directly unless you perform a manual redraw.",
    "sb\\tThe sb argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_statusbar_set_text */
    "gtcaca_statusbar_set_text",
    "statusbar",
    "Set the text property of statusbar",
    "void gtcaca_statusbar_set_text(gtcaca_statusbar_widget_t *sb, const char *text)",
    "Sets the text attribute of the statusbar widget to the given value.",
    "sb\\tThe sb argument\\ntext\\tText label to display\\n",
    "Nothing."
  },
  {
    /* gtcaca_switch_draw */
    "gtcaca_switch_draw",
    "switch",
    "Draw the switch widget",
    "void gtcaca_switch_draw(gtcaca_switch_widget_t *sw)",
    "Renders the switch widget onto the caca canvas.\n"
    "Called automatically by the main loop; you normally do not need\n"
    "to call this directly unless you perform a manual redraw.",
    "sw\\tThe sw argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_switch_set_active */
    "gtcaca_switch_set_active",
    "switch",
    "Set the active property of switch",
    "void gtcaca_switch_set_active(gtcaca_switch_widget_t *sw, int active)",
    "Sets the active attribute of the switch widget to the given value.",
    "sw\\tThe sw argument\\nactive\\tNon-zero to activate\\n",
    "Nothing."
  },
  {
    /* gtcaca_switch_get_active */
    "gtcaca_switch_get_active",
    "switch",
    "Get the active property of switch",
    "int gtcaca_switch_get_active(gtcaca_switch_widget_t *sw)",
    "Returns the current active attribute of the switch widget.",
    "sw\\tThe sw argument\\n",
    "0 on success, non-zero on error."
  },
  {
    /* gtcaca_switch_cb_register */
    "gtcaca_switch_cb_register",
    "switch",
    "Register a callback for switch events",
    "void gtcaca_switch_cb_register(gtcaca_switch_widget_t *sw, gtcaca_switch_cb_t cb, void *userdata)",
    "Registers a callback function that is invoked whenever a key event\n"
    "reaches the switch widget. The callback receives the widget pointer,\n"
    "the key code, and the userdata pointer supplied here.",
    "sw\\tThe sw argument\\ncb\\tCallback function pointer\\nuserdata\\tUser-supplied pointer passed back in callbacks\\n",
    "Nothing."
  },
  {
    /* gtcaca_textlist_new */
    "gtcaca_textlist_new",
    "textlist",
    "Create a new textlist widget",
    "gtcaca_textlist_widget_t * gtcaca_textlist_new(gtcaca_widget_t *parent, int x, int y)",
    "Allocates and initialises a new textlist widget.\n"
    "The widget is added to the global widget list and will be drawn\n"
    "on the next redraw cycle. Provide x, y to configure it.\n"
    "Returns NULL if memory allocation fails.",
    "parent\\tParent widget\\nx\\tX position relative to parent\\ny\\tY position relative to parent\\n",
    "Pointer to the newly allocated widget, or NULL on allocation failure."
  },
  {
    /* gtcaca_textlist_widget_set_view_size */
    "gtcaca_textlist_widget_set_view_size",
    "textlist",
    "Perform textlist widget set view size operation",
    "void gtcaca_textlist_widget_set_view_size(gtcaca_textlist_widget_t *widget, unsigned int view_size)",
    "Perform textlist widget set view size operation.",
    "widget\\tTarget widget\\nview_size\\tNumber of visible rows in the list\\n",
    "Nothing."
  },
  {
    /* gtcaca_textlist_key_cb_register */
    "gtcaca_textlist_key_cb_register",
    "textlist",
    "Register a callback for textlist key events",
    "int gtcaca_textlist_key_cb_register(gtcaca_textlist_widget_t *widget, gtcaca_textlist_key_cb_t key_cb, void *userdata)",
    "Registers a callback function that is invoked whenever a key event\n"
    "reaches the textlist key widget. The callback receives the widget pointer,\n"
    "the key code, and the userdata pointer supplied here.",
    "widget\\tTarget widget\\nkey_cb\\tCallback function pointer\\nuserdata\\tUser-supplied pointer passed back in callbacks\\n",
    "0 on success, non-zero on error."
  },
  {
    /* gtcaca_textlist_append */
    "gtcaca_textlist_append",
    "textlist",
    "Append an item to the textlist",
    "void gtcaca_textlist_append(gtcaca_textlist_widget_t *textlist, char *item)",
    "Appends a new entry to the textlist. The string is copied internally.",
    "textlist\\tThe textlist argument\\nitem\\tItem string to add\\n",
    "Nothing."
  },
  {
    /* gtcaca_textlist_selection_up */
    "gtcaca_textlist_selection_up",
    "textlist",
    "Perform textlist selection up operation",
    "void gtcaca_textlist_selection_up(gtcaca_textlist_widget_t *textlist)",
    "Perform textlist selection up operation.",
    "textlist\\tThe textlist argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_textlist_selection_down */
    "gtcaca_textlist_selection_down",
    "textlist",
    "Perform textlist selection down operation",
    "void gtcaca_textlist_selection_down(gtcaca_textlist_widget_t *textlist)",
    "Perform textlist selection down operation.",
    "textlist\\tThe textlist argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_textlist_get_text_selected */
    "gtcaca_textlist_get_text_selected",
    "textlist",
    "Perform textlist get text selected operation",
    "char * gtcaca_textlist_get_text_selected(gtcaca_textlist_widget_t *textlist)",
    "Perform textlist get text selected operation.",
    "textlist\\tThe textlist argument\\n",
    "Pointer to the string, or NULL if not available."
  },
  {
    /* gtcaca_textlist_draw */
    "gtcaca_textlist_draw",
    "textlist",
    "Draw the textlist widget",
    "void gtcaca_textlist_draw(gtcaca_textlist_widget_t *textlist)",
    "Renders the textlist widget onto the caca canvas.\n"
    "Called automatically by the main loop; you normally do not need\n"
    "to call this directly unless you perform a manual redraw.",
    "textlist\\tThe textlist argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_textlist_clear */
    "gtcaca_textlist_clear",
    "textlist",
    "Clear all items from the textlist",
    "void gtcaca_textlist_clear(gtcaca_textlist_widget_t *textlist)",
    "Removes all entries from the textlist and resets its selection\n"
    "index to zero. The widget will be blank after the next draw cycle.",
    "textlist\\tThe textlist argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_textview_draw */
    "gtcaca_textview_draw",
    "textview",
    "Draw the textview widget",
    "void gtcaca_textview_draw(gtcaca_textview_widget_t *tv)",
    "Renders the textview widget onto the caca canvas.\n"
    "Called automatically by the main loop; you normally do not need\n"
    "to call this directly unless you perform a manual redraw.",
    "tv\\tThe tv argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_textview_append */
    "gtcaca_textview_append",
    "textview",
    "Append an item to the textview",
    "void gtcaca_textview_append(gtcaca_textview_widget_t *tv, const char *line)",
    "Appends a new entry to the textview. The string is copied internally.",
    "tv\\tThe tv argument\\nline\\tText line to append\\n",
    "Nothing."
  },
  {
    /* gtcaca_textview_clear */
    "gtcaca_textview_clear",
    "textview",
    "Clear all items from the textview",
    "void gtcaca_textview_clear(gtcaca_textview_widget_t *tv)",
    "Removes all entries from the textview and resets its selection\n"
    "index to zero. The widget will be blank after the next draw cycle.",
    "tv\\tThe tv argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_textview_set_mode */
    "gtcaca_textview_set_mode",
    "textview",
    "Set the mode property of textview",
    "void gtcaca_textview_set_mode(gtcaca_textview_widget_t *tv, gtcaca_textview_mode_t mode)",
    "Sets the mode attribute of the textview widget to the given value.",
    "tv\\tThe tv argument\\nmode\\tThe mode argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_textview_key_cb_register */
    "gtcaca_textview_key_cb_register",
    "textview",
    "Register a callback for textview key events",
    "int gtcaca_textview_key_cb_register(gtcaca_textview_widget_t *widget, gtcaca_textview_key_cb_t key_cb, void *userdata)",
    "Registers a callback function that is invoked whenever a key event\n"
    "reaches the textview key widget. The callback receives the widget pointer,\n"
    "the key code, and the userdata pointer supplied here.",
    "widget\\tTarget widget\\nkey_cb\\tCallback function pointer\\nuserdata\\tUser-supplied pointer passed back in callbacks\\n",
    "0 on success, non-zero on error."
  },
  {
    /* gtcaca_widget_position_size_parent */
    "gtcaca_widget_position_size_parent",
    "widget",
    "Perform widget position size parent operation",
    "void gtcaca_widget_position_size_parent(gtcaca_widget_t *parent, gtcaca_widget_t *widget, int x, int y)",
    "Perform widget position size parent operation.",
    "parent\\tParent widget\\nwidget\\tTarget widget\\nx\\tX position relative to parent\\ny\\tY position relative to parent\\n",
    "Nothing."
  },
  {
    /* gtcaca_widget_printall */
    "gtcaca_widget_printall",
    "widget",
    "Perform widget printall operation",
    "void gtcaca_widget_printall(void)",
    "Perform widget printall operation.",
    "",
    "Nothing."
  },
  {
    /* gtcaca_widget_colorize_from_parent */
    "gtcaca_widget_colorize_from_parent",
    "widget",
    "Perform widget colorize from parent operation",
    "void gtcaca_widget_colorize_from_parent(gtcaca_widget_t *widget)",
    "Perform widget colorize from parent operation.",
    "widget\\tTarget widget\\n",
    "Nothing."
  },
  {
    /* gtcaca_widget_colorize */
    "gtcaca_widget_colorize",
    "widget",
    "Perform widget colorize operation",
    "void gtcaca_widget_colorize(gtcaca_widget_t *widget)",
    "Perform widget colorize operation.",
    "widget\\tTarget widget\\n",
    "Nothing."
  },
  {
    /* gtcaca_widget_is_focusable */
    "gtcaca_widget_is_focusable",
    "widget",
    "Perform widget is focusable operation",
    "int gtcaca_widget_is_focusable(gtcaca_widget_t *widget)",
    "Perform widget is focusable operation.",
    "widget\\tTarget widget\\n",
    "0 on success, non-zero on error."
  },
  {
    /* gtcaca_widget_show */
    "gtcaca_widget_show",
    "widget",
    "Show the widget widget",
    "void gtcaca_widget_show(gtcaca_widget_t *widget)",
    "Show the widget widget.",
    "widget\\tTarget widget\\n",
    "Nothing."
  },
  {
    /* gtcaca_widget_hide */
    "gtcaca_widget_hide",
    "widget",
    "Hide the widget widget",
    "void gtcaca_widget_hide(gtcaca_widget_t *widget)",
    "Hide the widget widget.",
    "widget\\tTarget widget\\n",
    "Nothing."
  },
  {
    /* gtcaca_window_draw */
    "gtcaca_window_draw",
    "window",
    "Draw the window widget",
    "void gtcaca_window_draw(gtcaca_window_widget_t *win)",
    "Renders the window widget onto the caca canvas.\n"
    "Called automatically by the main loop; you normally do not need\n"
    "to call this directly unless you perform a manual redraw.",
    "win\\tThe win argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_window_set_focus */
    "gtcaca_window_set_focus",
    "window",
    "Set the focus property of window",
    "void gtcaca_window_set_focus(gtcaca_window_widget_t *win)",
    "Sets the focus attribute of the window widget to the given value.",
    "win\\tThe win argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_window_get_current_focus */
    "gtcaca_window_get_current_focus",
    "window",
    "Set focus to the window get current widget",
    "gtcaca_window_widget_t * gtcaca_window_get_current_focus(void)",
    "Set focus to the window get current widget.",
    "",
    "Pointer to the newly allocated widget, or NULL on allocation failure."
  },
  {
    /* gtcaca_window_get_next */
    "gtcaca_window_get_next",
    "window",
    "Get the next property of window",
    "gtcaca_window_widget_t * gtcaca_window_get_next(gtcaca_window_widget_t *win)",
    "Returns the current next attribute of the window widget.",
    "win\\tThe win argument\\n",
    "Pointer to the newly allocated widget, or NULL on allocation failure."
  },
  {
    /* gtcaca_window_get_prev */
    "gtcaca_window_get_prev",
    "window",
    "Get the prev property of window",
    "gtcaca_window_widget_t * gtcaca_window_get_prev(gtcaca_window_widget_t *win)",
    "Returns the current prev attribute of the window widget.",
    "win\\tThe win argument\\n",
    "Pointer to the newly allocated widget, or NULL on allocation failure."
  },
  {
    /* gtcaca_window_set_focused_child */
    "gtcaca_window_set_focused_child",
    "window",
    "Perform window set focused child operation",
    "void gtcaca_window_set_focused_child(gtcaca_window_widget_t *win, gtcaca_widget_t *child)",
    "Perform window set focused child operation.",
    "win\\tThe win argument\\nchild\\tThe child argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_window_set_default */
    "gtcaca_window_set_default",
    "window",
    "Set the default property of window",
    "void gtcaca_window_set_default(gtcaca_window_widget_t *win, gtcaca_widget_t *widget)",
    "Sets the default attribute of the window widget to the given value.",
    "win\\tThe win argument\\nwidget\\tTarget widget\\n",
    "Nothing."
  },
  {
    /* gtcaca_window_focus_next_child */
    "gtcaca_window_focus_next_child",
    "window",
    "Perform window focus next child operation",
    "void gtcaca_window_focus_next_child(gtcaca_window_widget_t *win)",
    "Perform window focus next child operation.",
    "win\\tThe win argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_window_focus_prev_child */
    "gtcaca_window_focus_prev_child",
    "window",
    "Perform window focus prev child operation",
    "void gtcaca_window_focus_prev_child(gtcaca_window_widget_t *win)",
    "Perform window focus prev child operation.",
    "win\\tThe win argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_window_set_close_animation */
    "gtcaca_window_set_close_animation",
    "window",
    "Perform window set close animation operation",
    "void gtcaca_window_set_close_animation(gtcaca_window_widget_t *win, gtcaca_window_close_anim_t anim, gtcaca_widget_t *target)",
    "Perform window set close animation operation.",
    "win\\tThe win argument\\nanim\\tThe anim argument\\ntarget\\tThe target argument\\n",
    "Nothing."
  },
  {
    /* gtcaca_window_close */
    "gtcaca_window_close",
    "window",
    "Perform window close operation",
    "void gtcaca_window_close(gtcaca_window_widget_t *win)",
    "Perform window close operation.",
    "win\\tThe win argument\\n",
    "Nothing."
  },
};

const int gtcaca_api_count = (int)(sizeof(gtcaca_api) / sizeof(gtcaca_api[0]));
